### ISSUE TITLE
Blogikirjoitus?

### ISSUE THREAD

**Issue by pitkant** [tts/minatutkintweets#1]
Hei, repositorysi ponnahti omaan GitHub-feediini. #minätutkin ja #jagforskar-twiittien tarkasteluhan on aiheena erittäin ajankohtainen ja Twitterin keskustelujen koostaminen ja käsitteleminen aihe, josta ei suomen kielellä ole koskaan liikaa materiaalia.

Haluaisitko kirjoittaa aiheesta suomeksi ja/tai englanniksi avoimen (hallinnollisen) datan käsittelyyn keskittyvän rOpenGov-ryhmän blogiin (http://ropengov.org/fi/)? Kirjoitukseen voi hyvin sisällyttää R-koodia ja visualisointeja, esimerkiksi sanapilviä. 

Muutenkin sinulla näyttäisi olevan paljon siistejä R-juttuja esimerkiksi HRI:n avoimeen dataan liittyen. 👍

**Comment by tts** [comment]
Hei, kiitos mukavasta palautteesta ja pyynnöstä! Mikäpä ettei, voin kirjoittaa - varsinkin, jos aikataulu voi olla melko väljä :)

**Comment by pitkant** [comment]
Loistava homma! Blogi on toteutettu blogdownilla ja yksittäiset kirjoitukset ovat markdown (.md) tai Rmarkdown (.Rmd) -tiedostoja. 

- Esimerkki .Rmd-kirjoituksesta: https://github.com/rOpenGov/homepage/blob/master/content/post/2021-06-04-iotables-cran-release.en/index.en.Rmd
- Esimerkki .md-kirjoituksesta: https://raw.githubusercontent.com/rOpenGov/homepage/master/content/post/2014-01-29-stan-kilpisjarvi/index.fi.md

Voin hoitaa stilisoinnit puolestasi tai sitten voit tehdä pull requestin homepage-repoomme content/post -kansioon: https://github.com/rOpenGov/homepage

**Comment by tts** [comment]
Arkailin pull requestin kanssa, kun en ole kai ennen tehnyt, en ainakaan tällaisessa yhteydessä. Edellyttääkö se siis koko reponne forkausta ensin vai miten tuo toimii? 

Oli miten oli, jos voit napata tekstini https://github.com/tts/minatutkintweets/blob/main/blogi.md niin se olisi kai yksinkertaisinta.

**Comment by pitkant** [comment]
Hei, kiitos paljon, näyttää erittäin hyvältä! Laitoin kirjoituksen nettisivuille mutta voisin laittaa siitä infoa Twitteriin huomenna aamulla.

http://ropengov.org/fi/2021/10/mina-tutkin/
